### ISSUE TITLE
subprocess.CalledProcessError occurred during installation

### ISSUE THREAD

**Issue by sparkandshine** [steinwurf/fifi-python#15]
I tried to install `fifi` with `sudo pip install fifi` on MacOS, but encountered the error `subprocess.CalledProcessError`, as shown below,

```
      File "/private/tmp/pip-build-fKM_Ii/fifi/setup.py", line 67, in run
        check_call(build_cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python', 'waf', 'configure', '--options=install_path=installed_binaries,cxx_mkspec=cxx_default_x64', 'build', 'install']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-fKM_Ii/fifi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-nYHnkF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-fKM_Ii/fifi/
```

I am pretty sure Xcode and Command-line Tools have been installed successfully on my machine. 

How do fix it?

------

I tried to build it from source, but it raised the following error.

```
$ python waf configure
Checking for program 'git'               : /usr/local/bin/git 
Resolve dependency waf-tools             : /Users/sparkandshine/git/fifi-python/bundle_dependencies/waf-tools-51dff5/3.19.0 
Resolve dependency boost                 : /Users/sparkandshine/git/fifi-python/bundle_dependencies/boost-abe3de/2.3.0 
Resolve dependency fifi                  : Command ['/usr/local/bin/git', 'clone', 'https://github.com/steinwurf/fifi.git', '/Users/sparkandshine/git/fifi-python/bundle_dependencies/fifi-8960fd/master'] returned 128
```

**Comment by mortenvp** [comment]
Hi @sparkandshine 
I think we need to update the readme :)

If you are a student, teacher or researcher you need our research license to access the fifi repository. It is a private repository.

If you intend to use fifi for commercial purposes you need a commercial evaluation license instead. In both cases, check it here:

http://steinwurf.com/license.html

After obtain a license you should be able to build from source.

@jpihl do we still support the pip packages?

**Comment by sparkandshine** [comment]
@mortenvp Thanks for this update.

I've just requested a license from [http://steinwurf.com/license.html](http://steinwurf.com/license.html).

**Comment by sparkandshine** [comment]
@mortenvp @jpihl 

I tried to install `fifi`, but encountered the following issues.

```
$ git clone https://github.com/steinwurf/fifi.git
$ cd fifi

$ python waf config.py 
No function config.py defined in /Users/sparkandshine/git/fifi/wscript

$ python waf build
The project was not configured: run "waf configure" first!
```

How do I install `fifi`?

**Comment by petya2164** [comment]
Just follow the steps here:
https://github.com/steinwurf/fifi-python#id6
It should be `python waf configure`

**Comment by petya2164** [comment]
I updated the README here, and I am closing this issue (and the issue tracker).
Please use our mailing list in the future!
